// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn0GfVlm3Wt1LVsWWCTg9PBhth9xZp-Wg',
    appId: '1:70539885378:web:2cc6c21675e9a9a224a6db',
    messagingSenderId: '70539885378',
    projectId: 'formulario-app-68aab',
    authDomain: 'formulario-app-68aab.firebaseapp.com',
    storageBucket: 'formulario-app-68aab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-g3R4MxjezoYVVxoTITcMC_art2Jk_c',
    appId: '1:70539885378:android:6eab3762125618c024a6db',
    messagingSenderId: '70539885378',
    projectId: 'formulario-app-68aab',
    storageBucket: 'formulario-app-68aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3v71BUHH6BG0w8MgRylvug1ofPuFgEE',
    appId: '1:70539885378:ios:b5a5061c5e11722d24a6db',
    messagingSenderId: '70539885378',
    projectId: 'formulario-app-68aab',
    storageBucket: 'formulario-app-68aab.firebasestorage.app',
    iosBundleId: 'com.nikolasiba.formulariosApp',
  );
}
